return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      delay = 300,
      icons = {
        mappings = false,
        breadcrumb = ">",
        separator = "->",
        group = "+",
        keys = {
          C = "Ctrl-",
          M = "Alt-",
          D = "Cmd-",
          S = "Shift-",
          NL = "Enter",
          ScrollWheelDown = "WheelDown",
          ScrollWheelUp = "WheelUp",
          F1 = "F1", F2 = "F2", F3 = "F3", F4 = "F4",
          F5 = "F5", F6 = "F6", F7 = "F7", F8 = "F8",
          F9 = "F9", F10 = "F10", F11 = "F11", F12 = "F12",
          Space = "Space",
          Esc = "Esc",
          CR = "Enter",
          Tab = "Tab",
          BS = "Backspace",
          Up = "Up",
          Down = "Down",
          Left = "Left",
          Right = "Right",
        },
      },
      spec = {
        { "<leader>f", group = "Find" },
        { "<leader>c", group = "Code" },
        { "<leader>d", group = "Diagnostics" },
        { "<leader>l", group = "Lean" },
      },
    },
  },
}
